apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eurotrip
  namespace: eurotrip
spec:
  ingressClassName: nginx
  rules:
  - host: eurotrip.jaco.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eurotrip
            port:
              number: 80

